# Generated by Django 5.1.7 on 2025-05-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número da Sala')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame')], max_length=10, verbose_name='Tipo')),
                ('equipamentos', models.TextField(blank=True, null=True, verbose_name='Equipamentos Instalados')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
