# Generated by Django 5.2 on 2025-05-11 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='teleconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='usuarios.teleconsulta'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='teleconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='usuarios.teleconsulta'),
        ),
        migrations.AddField(
            model_name='receita',
            name='teleconsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='usuarios.teleconsulta'),
        ),
        migrations.AlterField(
            model_name='atestado',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='usuarios.consulta'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='usuarios.consulta'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='usuarios.consulta'),
        ),
    ]
