# Generated by Django 5.2 on 2025-05-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_atestado_teleconsulta_laudo_teleconsulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/resultados_exames/')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='usuarios.exame')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_exames', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_exames_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemResultadoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='resultados_exames_imagens/')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='usuarios.resultadoexame')),
            ],
        ),
    ]
