# Generated by Django 5.1.7 on 2025-05-03 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame')], max_length=20)),
                ('tipo_exame', models.CharField(blank=True, choices=[('radiografia', 'Radiografia'), ('ultrassonografia', 'Ultrassonografia'), ('tomografia', 'Tomografia Computadorizada'), ('mamografia', 'Mamografia'), ('doppler', 'Doppler')], max_length=30, null=True)),
                ('data', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('duracao_procedimento', models.PositiveIntegerField(help_text='Duração em minutos')),
                ('ativo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(blank=True, limit_choices_to={'role': 'medico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.sala')),
            ],
        ),
    ]
