# Generated by Django 5.2 on 2025-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_resultadoexame_imagemresultadoexame'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoexame',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='resultados_exames_imagens/'),
        ),
    ]
