# Generated by Django 5.1.7 on 2025-05-03 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
    ]
