# Generated by Django 5.2 on 2025-05-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_receitafinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fornecedor', models.CharField(max_length=100)),
            ],
        ),
    ]
