# Generated by Django 5.1.7 on 2025-05-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_consulta_data_cancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status_manual',
            field=models.CharField(choices=[('livre', 'Livre'), ('agendado', 'Agendado'), ('bloqueado', 'Bloqueado')], default='livre', max_length=20),
        ),
    ]
