# Generated by Django 5.1.7 on 2025-05-03 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_agenda_status_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='usuarios.agenda'),
        ),
    ]
