# Generated by Django 5.1.7 on 2025-05-04 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_consulta_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atestados', to='usuarios.consulta')),
                ('medico', models.ForeignKey(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='atestados_emitidos', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='atestados_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to='usuarios.consulta')),
                ('medico', models.ForeignKey(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='laudos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='laudos_recebidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='usuarios.consulta')),
                ('medico', models.ForeignKey(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='receitas_emitidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='receitas_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
