# Generated by Django 5.2 on 2025-05-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_atestado_laudo_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True)),
                ('tratamentos', models.TextField(blank=True)),
                ('historico_cirurgias', models.TextField(blank=True)),
                ('observacoes_medicas', models.TextField(blank=True)),
                ('paciente', models.OneToOneField(limit_choices_to={'tipo': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
