# Generated by Django 5.2 on 2025-05-04 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_prontuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('em_andamento', 'Em atendimento'), ('finalizada', 'Finalizada')], default='agendada', max_length=20)),
                ('observacoes_visiveis', models.TextField(blank=True, null=True)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('encaminhamento', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('radiografia', 'Radiografia (Raio-X)'), ('ultrassonografia', 'Ultrassonografia'), ('tomografia', 'Tomografia Computadorizada (TC)'), ('mamografia', 'Mamografia'), ('doppler', 'Doppler (Ultrassom Vascular)')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas_de_exames', to='usuarios.agenda')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_cancelados', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='exames_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='exames_como_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teleconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('em_andamento', 'Em atendimento'), ('finalizada', 'Finalizada')], default='agendada', max_length=20)),
                ('observacoes_visiveis', models.TextField(blank=True, null=True)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('encaminhamento', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=125.0, max_digits=8)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas_de_teleconsultas', to='usuarios.agenda')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teleconsultas_canceladas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas_como_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas_como_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
