# Generated by Django 5.2 on 2025-05-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_exame_teleconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='atestado',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/atestados/'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/laudos/'),
        ),
        migrations.AddField(
            model_name='receita',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/receitas/'),
        ),
    ]
